#### KBM - 主配置
#
# 使用本插件前务必确保你已经完整的看完了插件文档
# 插件文档 & 参考配置, 请见群(673765463)文件
#
# 以下是配置文件:


# ======================================
# 击退同步
# 简介: 修复高延迟玩家地面状态判定不准确的问题
# ======================================
kb_sync:
  # 是否启用? (需要ProtocolLib)
  enabled: false


# ======================================
# 服务器端命中检测
# 简介: 开启此功能后玩家的攻击是否命中由服务器端判定
# ======================================
# 注意: 此功能与 packet.misplace 不兼容
# 注意: 此功能可能导致一些插件的攻击事件出错, 详见文档!
server_side_hit_detection:
  # 是否启用? (需要ProtocolLib)
  enabled: false

  # --------------------------------------
  # 攻击碰撞箱大小设置
  # --------------------------------------
  hitbox_size:
    # 碰撞箱长度/宽度
    # 游戏原版数值: 1.8版本 = 0.8, 1.9+版本 = 0.6
    length: 0.8
    # 碰撞箱高度
    # 游戏原版数值: 1.8版本 = 1.9, 1.9+版本 = 1.8
    height: 1.9

  # --------------------------------------
  # 最大攻击距离
  # --------------------------------------
  max_distance:
    # 生存/冒险模式
    survival: 3.0
    # 创造模式
    creative: 5.0
