# ============================
# 水平方向击退设置
# ============================
horizontal:
  # 地面击退距离
  ground: 0.4
  # 空中击退距离
  air: 0.4
  # 疾跑时增加的击退距离
  sprint_extra: 0.5
  # 投掷物造成的击退距离的乘以倍数
  projectile_multiplier: 1.0

# ============================
# 垂直方向击退设置
# ============================
vertical:
  # 地面击退距离
  ground: 0.36075
  # 空中击退距离
  air: 0.24775
  # 疾跑时增加的击退距离
  sprint_extra: 0.1
  # 投掷物造成的击退距离的乘以倍数
  projectile_multiplier: 1.0

# ============================
# 数据包修改
# ============================
packet:
  # ----------------------------
  # 将位置更新包错位
  # ----------------------------
  misplace:
    # 是否开启错位
    enabled: false
    # 错位距离
    distance: 0.1 # (单位: 格)
  # ----------------------------
  # 延迟发送位置更新包
  # ----------------------------
  delay:
    # 是否开启延迟发送
    enabled: false
    # 延迟发送的时间
    ticks: 2 # (单位: 游戏刻)

# ============================
# 重置疾跑
# ============================
stop_sprint: true

# ============================
# Y 轴高度限制
# ============================
y_limit: 0.675 # (单位: 格)

# ============================
# 攻击速度
# ============================
hit_delay: 20 # (单位: 游戏刻)