# ===========================
# 使用本插件前请确保你已经完整的看完了插件文档
# 插件文档 & 参考配置, 请见群(673765463)文件
# ===========================

horizontal:
  # 地面水平方向击退距离
  ground: 0.4
  # 空中水平方向击退距离
  air: 0.4
  # 疾跑时增加的水平方向击退距离
  sprint_extra: 0.5

vertical:
  # 地面垂直方向击退距离
  ground: 0.36075
  # 空中垂直方向击退距离
  air: 0.24775
  # 疾跑时增加的垂直方向击退距离
  sprint_extra: 0.1

projectile:
  # 是否启用投掷物击退修改
  enabled: false
  # 投掷物造成的水平方向击退距离的乘以倍数
  horizontal_multiplier: 1.0
  # 投掷物造成的垂直方向击退距离的乘以倍数
  vertical_multiplier: 1.0
  # 是否使用投掷物发射者的位置来计算击退方向
  direction_override: false

packet:
  misplace:
    # 是否将位置更新包错位
    enabled: false
    # 错位距离 (单位: 格)
    distance: 0.1
  delay:
    # 是否延迟发送位置更新包
    enabled: false
    # 延迟发送的时间 (单位: 游戏刻)
    ticks: 2

# 重置疾跑
stop_sprint: true

# 击退造成的 Y 轴高度限制 (单位: 格)
y_limit: 0.675

# 攻击间隔 (单位: 游戏刻)
hit_delay: 20

potion:
  # 是否启用投掷型药水运动修改
  enabled: false
  # 药水的水平方向运动的乘以倍数
  horizontal_multiplier: 1.05
  # 药水的垂直方向运动的乘以倍数
  vertical_multiplier: 1.0
  # 药水命中自身时的强度补偿倍数
  compensation_multiplier: 1.15

modern:
  # 是否让攻击冷却影响击退
  cooldown_affects_kb: true
  # 是否应用下界合金击退抗性
  netherite_kb_resistance: true