name: KnockbackManager
main: me.dw1e.kbm.KnockbackManager
version: 2.3.0
author: dw1e
website: https://github.com/dw1e/KnockbackManager
softdepend: [ ProtocolLib, PlaceholderAPI ]
api-version: 1.16

commands:
  kbm:
    aliases: [ kb, knockback ]

permissions:
  kbm.use:
    default: op
